param profiles_zus1rcrcwebsitedevv1fd_name string = 'zus1rcrcwebsitedevv1fd'
param frontdoorWebApplicationFirewallPolicies_zus1rcrcwebsitedevv1wafp_externalid string = '/subscriptions/1af779b2-7582-4d0a-afee-4596ea7d480f/resourceGroups/zus1-rc-rcwebsite-dev-v1-rg/providers/Microsoft.Network/frontdoorWebApplicationFirewallPolicies/zus1rcrcwebsitedevv1wafp'

resource profiles_zus1rcrcwebsitedevv1fd_name_resource 'Microsoft.Cdn/profiles@2025-04-15' = {
  name: profiles_zus1rcrcwebsitedevv1fd_name
  location: 'Global'
  tags: {
    app: 'rcwebsite'
  }
  sku: {
    name: 'Standard_AzureFrontDoor'
  }
  kind: 'frontdoor'
  properties: {
    originResponseTimeoutSeconds: 60
  }
}

resource profiles_zus1rcrcwebsitedevv1fd_name_profiles_zus1rcrcwebsitedevv1fd_name_ep 'Microsoft.Cdn/profiles/afdendpoints@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_resource
  name: '${profiles_zus1rcrcwebsitedevv1fd_name}ep'
  location: 'Global'
  tags: {
    app: 'rcwebsite'
  }
  properties: {
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    enabledState: 'Enabled'
  }
}

resource profiles_zus1rcrcwebsitedevv1fd_name_rebelcorpo_com 'Microsoft.Cdn/profiles/customdomains@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_resource
  name: 'rebelcorpo-com'
  properties: {
    hostName: 'rebelcorpo.com'
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      minimumTlsVersion: 'TLS12'
      cipherSuiteSetType: 'TLS12_2022'
    }
  }
}

resource profiles_zus1rcrcwebsitedevv1fd_name_www_rebelcorpo_com 'Microsoft.Cdn/profiles/customdomains@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_resource
  name: 'www-rebelcorpo-com'
  properties: {
    hostName: 'www.rebelcorpo.com'
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      minimumTlsVersion: 'TLS12'
      cipherSuiteSetType: 'TLS12_2022'
    }
  }
}

resource profiles_zus1rcrcwebsitedevv1fd_name_og_container 'Microsoft.Cdn/profiles/origingroups@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_resource
  name: 'og-container'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 0
    }
    trafficRestorationTimeToHealedOrNewEndpointsInMinutes: 10
    sessionAffinityState: 'Disabled'
  }
}

resource profiles_zus1rcrcwebsitedevv1fd_name_og_function 'Microsoft.Cdn/profiles/origingroups@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_resource
  name: 'og-function'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 0
    }
    trafficRestorationTimeToHealedOrNewEndpointsInMinutes: 10
    sessionAffinityState: 'Disabled'
  }
}

resource profiles_zus1rcrcwebsitedevv1fd_name_og_container_origin_container 'Microsoft.Cdn/profiles/origingroups/origins@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_og_container
  name: 'origin-container'
  properties: {
    hostName: 'zus1-rc-rcwebsite-dev-v1-ca.kindcoast-79a5c309.eastus.azurecontainerapps.io'
    httpPort: 80
    httpsPort: 443
    originHostHeader: 'zus1-rc-rcwebsite-dev-v1-ca.kindcoast-79a5c309.eastus.azurecontainerapps.io'
    priority: 1
    weight: 1000
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
  }
  dependsOn: [
    profiles_zus1rcrcwebsitedevv1fd_name_resource
  ]
}

resource profiles_zus1rcrcwebsitedevv1fd_name_og_function_origin_function 'Microsoft.Cdn/profiles/origingroups/origins@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_og_function
  name: 'origin-function'
  properties: {
    hostName: 'zus1-rc-rcwebsite-dev-v1-fa.azurewebsites.net'
    httpPort: 80
    httpsPort: 443
    originHostHeader: 'zus1-rc-rcwebsite-dev-v1-fa.azurewebsites.net'
    priority: 1
    weight: 1000
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
  }
  dependsOn: [
    profiles_zus1rcrcwebsitedevv1fd_name_resource
  ]
}

resource profiles_zus1rcrcwebsitedevv1fd_name_profiles_zus1rcrcwebsitedevv1fd_name_waf 'Microsoft.Cdn/profiles/securitypolicies@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_resource
  name: '${profiles_zus1rcrcwebsitedevv1fd_name}waf'
  properties: {
    parameters: {
      wafPolicy: {
        id: frontdoorWebApplicationFirewallPolicies_zus1rcrcwebsitedevv1wafp_externalid
      }
      type: 'WebApplicationFirewall'
      associations: [
        {
          domains: [
            {
              id: profiles_zus1rcrcwebsitedevv1fd_name_rebelcorpo_com.id
            }
            {
              id: profiles_zus1rcrcwebsitedevv1fd_name_www_rebelcorpo_com.id
            }
          ]
          patternsToMatch: [
            '/*'
          ]
        }
      ]
    }
  }
}

resource profiles_zus1rcrcwebsitedevv1fd_name_profiles_zus1rcrcwebsitedevv1fd_name_ep_route_api 'Microsoft.Cdn/profiles/afdendpoints/routes@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_profiles_zus1rcrcwebsitedevv1fd_name_ep
  name: 'route-api'
  properties: {
    customDomains: [
      {
        id: profiles_zus1rcrcwebsitedevv1fd_name_www_rebelcorpo_com.id
      }
    ]
    originGroup: {
      id: profiles_zus1rcrcwebsitedevv1fd_name_og_function.id
    }
    ruleSets: []
    supportedProtocols: [
      'Https'
    ]
    patternsToMatch: [
      '/api/*'
    ]
    forwardingProtocol: 'MatchRequest'
    linkToDefaultDomain: 'Disabled'
    httpsRedirect: 'Enabled'
    enabledState: 'Enabled'
  }
  dependsOn: [
    profiles_zus1rcrcwebsitedevv1fd_name_resource
  ]
}

resource profiles_zus1rcrcwebsitedevv1fd_name_profiles_zus1rcrcwebsitedevv1fd_name_ep_route_default 'Microsoft.Cdn/profiles/afdendpoints/routes@2025-04-15' = {
  parent: profiles_zus1rcrcwebsitedevv1fd_name_profiles_zus1rcrcwebsitedevv1fd_name_ep
  name: 'route-default'
  properties: {
    customDomains: [
      {
        id: profiles_zus1rcrcwebsitedevv1fd_name_www_rebelcorpo_com.id
      }
    ]
    originGroup: {
      id: profiles_zus1rcrcwebsitedevv1fd_name_og_container.id
    }
    ruleSets: []
    supportedProtocols: [
      'Https'
    ]
    patternsToMatch: [
      '/*'
    ]
    forwardingProtocol: 'MatchRequest'
    linkToDefaultDomain: 'Disabled'
    httpsRedirect: 'Enabled'
    enabledState: 'Enabled'
  }
  dependsOn: [
    profiles_zus1rcrcwebsitedevv1fd_name_resource
  ]
}
