@description('Deploys Azure Front Door profile, endpoint, origins, routes, custom domains, and WAF policy if not already existing. Module is intended to run once; subsequent runs can be skipped via pre-check.')
param zLocation string
param azureSubscription string
param applicationName string
param devEnvironmentName string
param applicationVersion string
param tags object = {}

@description('Container App public FQDN (origin).')
param containerAppFqdn string
@description('Function App default hostname (origin).')
param functionAppHostname string

@description('Primary custom domain (e.g., www.example.com). Empty to skip domain creation.')
param primaryCustomDomain string = ''
@description('Optional additional custom domains.')
param additionalCustomDomains array = []

@description('Front Door SKU name.')
@allowed(['Standard_AzureFrontDoor', 'Premium_AzureFrontDoor'])
param afdSkuName string = 'Standard_AzureFrontDoor'

@description('Deploy and associate a WAF policy.')
param enableWaf bool = true
@description('Detection or Prevention mode for WAF policy.')
@allowed(['Detection', 'Prevention'])
param wafMode string = 'Prevention'

@description('If true, HTTPS redirect is enforced on routes.')
param enforceHttpsRedirect bool = true

@description('Route pattern for API (function app).')
param apiRoutePattern string = '/api/*'
@description('Route pattern for app (container app). Should remain catch-all.')
param appRoutePattern string = '/*'

// Naming
var profileName = toLower('${zLocation}${azureSubscription}${applicationName}${devEnvironmentName}${applicationVersion}fd')
var endpointName = '${profileName}ep'
var wafPolicyName = toLower('${zLocation}${azureSubscription}${applicationName}${devEnvironmentName}${applicationVersion}wafp')

// Derived collections
var domainInputs = empty(primaryCustomDomain) ? [] : union([primaryCustomDomain], additionalCustomDomains)
var createDomains = length(domainInputs) > 0
var httpsRedirectSetting = enforceHttpsRedirect ? 'Enabled' : 'Disabled'

// Profile
resource fdProfile 'Microsoft.Cdn/profiles@2025-04-15' = {
  name: profileName
  location: 'Global'
  sku: { name: afdSkuName }
  tags: union(tags, { component: 'frontdoor' })
  properties: { originResponseTimeoutSeconds: 60 }
}

// Endpoint
resource fdEndpoint 'Microsoft.Cdn/profiles/afdendpoints@2025-04-15' = {
  parent: fdProfile
  name: endpointName
  location: 'Global'
  tags: union(tags, { component: 'frontdoor-endpoint' })
  properties: {
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    enabledState: 'Enabled'
  }
}

// Origin groups
resource containerOriginGroup 'Microsoft.Cdn/profiles/origingroups@2025-04-15' = {
  parent: fdProfile
  name: 'og-container'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 0
    }
    trafficRestorationTimeToHealedOrNewEndpointsInMinutes: 10
    sessionAffinityState: 'Disabled'
  }
}

resource functionOriginGroup 'Microsoft.Cdn/profiles/origingroups@2025-04-15' = {
  parent: fdProfile
  name: 'og-function'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 0
    }
    trafficRestorationTimeToHealedOrNewEndpointsInMinutes: 10
    sessionAffinityState: 'Disabled'
  }
}

// Origins
resource containerOrigin 'Microsoft.Cdn/profiles/origingroups/origins@2025-04-15' = {
  parent: containerOriginGroup
  name: 'origin-container'
  properties: {
    hostName: containerAppFqdn
    httpPort: 80
    httpsPort: 443
    originHostHeader: containerAppFqdn
    priority: 1
    weight: 1000
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
  }
}

resource functionOrigin 'Microsoft.Cdn/profiles/origingroups/origins@2025-04-15' = {
  parent: functionOriginGroup
  name: 'origin-function'
  properties: {
    hostName: functionAppHostname
    httpPort: 80
    httpsPort: 443
    originHostHeader: functionAppHostname
    priority: 1
    weight: 1000
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
  }
}

// Custom domains (dynamic)
resource customDomains 'Microsoft.Cdn/profiles/customdomains@2025-04-15' = [
  for d in domainInputs: {
    parent: fdProfile
    name: replace(d, '.', '-')
    properties: {
      hostName: d
      tlsSettings: {
        certificateType: 'ManagedCertificate'
        minimumTlsVersion: 'TLS12'
        cipherSuiteSetType: 'TLS12_2022'
      }
    }
  }
]

// WAF Policy (only if enabled)
resource wafPolicy 'Microsoft.Network/frontdoorwebapplicationfirewallpolicies@2025-03-01' = if (enableWaf) {
  name: wafPolicyName
  location: 'Global'
  sku: { name: afdSkuName }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: wafMode
      requestBodyCheck: 'Enabled'
    }
    customRules: { rules: [] }
    managedRules: { managedRuleSets: [] }
  }
}

// Security policy association if WAF enabled and domains exist
@description('Security policy linking WAF policy to domains')
resource securityPolicy 'Microsoft.Cdn/profiles/securitypolicies@2025-04-15' = if (enableWaf && createDomains) {
  parent: fdProfile
  name: '${profileName}waf'
  properties: {
    parameters: {
      wafPolicy: { id: wafPolicy.id }
      type: 'WebApplicationFirewall'
      associations: [
        {
          // Build list of domain references by reconstructing resourceIds (avoids direct resource collection iteration limitation)
          domains: [
            for d in domainInputs: {
              id: resourceId('Microsoft.Cdn/profiles/customDomains', profileName, replace(d, '.', '-'))
            }
          ]
          patternsToMatch: ['/*']
        }
      ]
    }
  }
}

// Routes
resource apiRoute 'Microsoft.Cdn/profiles/afdendpoints/routes@2025-04-15' = {
  parent: fdEndpoint
  name: 'route-api'
  properties: {
    customDomains: createDomains ? [customDomains[0]] : []
    originGroup: { id: functionOriginGroup.id }
    ruleSets: []
    supportedProtocols: ['Https']
    patternsToMatch: [apiRoutePattern]
    forwardingProtocol: 'MatchRequest'
    linkToDefaultDomain: 'Disabled'
    httpsRedirect: httpsRedirectSetting
    enabledState: 'Enabled'
  }
}

resource appRoute 'Microsoft.Cdn/profiles/afdendpoints/routes@2025-04-15' = {
  parent: fdEndpoint
  name: 'route-app'
  properties: {
    customDomains: createDomains ? [customDomains[0]] : []
    originGroup: { id: containerOriginGroup.id }
    ruleSets: []
    supportedProtocols: ['Https']
    patternsToMatch: [appRoutePattern]
    forwardingProtocol: 'MatchRequest'
    linkToDefaultDomain: 'Disabled'
    httpsRedirect: httpsRedirectSetting
    enabledState: 'Enabled'
  }
}

output frontDoorEndpointHost string = fdEndpoint.properties.hostName
output frontDoorProfileId string = fdProfile.id
output frontDoorEndpointId string = fdEndpoint.id
output wafPolicyResourceId string = enableWaf ? (wafPolicy.id) : ''
