param subscriptionId string
param name string
param location string
param storageBlobContainerName string
param autoGeneratedDomainNameLabelScope string
param storageAccountName string
param sku string
param skuCode string
param workerSize string
param workerSizeId string
param numberOfWorkers string
param hostingPlanName string
param serverFarmResourceGroup string
param alwaysOn bool

resource name_resource 'Microsoft.Web/sites@2022-03-01' = {
  name: name
  kind: 'functionapp,linux'
  location: location
  tags: {}
  properties: {
    name: name
    siteConfig: {
      appSettings: [
        {
          name: 'DEPLOYMENT_STORAGE_CONNECTION_STRING'
          value: 'DefaultEndpointsProtocol=https;AccountName=${storageAccountName};AccountKey=${listKeys(resourceId('1af779b2-7582-4d0a-afee-4596ea7d480f','zus1-rc-rcwebsite-dev-v1-rg','Microsoft.Storage/storageAccounts',storageAccountName),'2022-05-01').keys[0].value};EndpointSuffix=core.windows.net'
        }
        {
          name: 'AzureWebJobsStorage'
          value: 'DefaultEndpointsProtocol=https;AccountName=${storageAccountName};AccountKey=${listKeys(resourceId('1af779b2-7582-4d0a-afee-4596ea7d480f','zus1-rc-rcwebsite-dev-v1-rg','Microsoft.Storage/storageAccounts',storageAccountName),'2022-05-01').keys[0].value};EndpointSuffix=core.windows.net'
        }
      ]
      cors: {
        allowedOrigins: [
          'https://portal.azure.com'
        ]
      }
    }
    clientAffinityEnabled: false
    virtualNetworkSubnetId: null
    autoGeneratedDomainNameLabelScope: autoGeneratedDomainNameLabelScope
    functionAppConfig: {
      deployment: {
        storage: {
          type: 'blobContainer'
          value: 'https://${storageAccountName}.blob.core.windows.net/${storageBlobContainerName}'
          authentication: {
            type: 'StorageAccountConnectionString'
            storageAccountConnectionStringName: 'DEPLOYMENT_STORAGE_CONNECTION_STRING'
          }
        }
      }
      scaleAndConcurrency: {
        maximumInstanceCount: 100
        instanceMemoryMB: 512
      }
      runtime: {
        name: 'dotnet-isolated'
        version: '8.0'
      }
    }
    publicNetworkAccess: 'Enabled'
    httpsOnly: true
    serverFarmId: '/subscriptions/${subscriptionId}/resourcegroups/${serverFarmResourceGroup}/providers/Microsoft.Web/serverfarms/${hostingPlanName}'
  }
  dependsOn: [
    hostingPlan
  ]
}

resource name_scm 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2022-09-01' = {
  parent: name_resource
  name: 'scm'
  properties: {
    allow: false
  }
}

resource name_ftp 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2022-09-01' = {
  parent: name_resource
  name: 'ftp'
  properties: {
    allow: false
  }
}

resource hostingPlan 'Microsoft.Web/serverfarms@2018-11-01' = {
  name: hostingPlanName
  location: location
  kind: 'linux'
  tags: {}
  properties: {
    name: hostingPlanName
    workerSize: workerSize
    workerSizeId: workerSizeId
    numberOfWorkers: numberOfWorkers
    reserved: true
    zoneRedundant: false
  }
  sku: {
    tier: sku
    name: skuCode
  }
  dependsOn: []
}

module StorageBlobContainerTemplate './nested_StorageBlobContainerTemplate.bicep' = {
  name: 'StorageBlobContainerTemplate'
  scope: resourceGroup(subscriptionId, 'zus1-rc-rcwebsite-dev-v1-rg')
  params: {
    resourceId_zus1_rc_rcwebsite_dev_v1_rg_Microsoft_Storage_storageAccounts_blobServices_parameters_storageAccountName_default: resourceId(
      'zus1-rc-rcwebsite-dev-v1-rg',
      'Microsoft.Storage/storageAccounts/blobServices',
      storageAccountName,
      'default'
    )
    storageAccountName: storageAccountName
    storageBlobContainerName: storageBlobContainerName
  }
  dependsOn: []
}
