on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com/prod-approval
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
      APPLICATION_VERSION: ${{ vars.APPLICATION_VERSION }}
      AZD_PIPELINE_PROVIDER: ${{ vars.AZD_PIPELINE_PROVIDER }}
      AZURE_CONTAINER_REGISTRY_ENDPOINT: ${{ vars.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      AZURE_DEV_ENVIRONMENT_NAME: ${{ vars.AZURE_DEV_ENVIRONMENT_NAME }}
      AZURE_UAT_ENVIRONMENT_NAME: ${{ vars.AZURE_UAT_ENVIRONMENT_NAME }}
      AZURE_PROD_ENVIRONMENT_NAME: ${{ vars.AZURE_PROD_ENVIRONMENT_NAME }}
      AZURE_PIPELINE_CLIENT_ID: ${{ vars.AZURE_PIPELINE_CLIENT_ID }}
      AZURE_RESOURCE_MY_BLAZOR_APP_ID: ${{ vars.AZURE_RESOURCE_MY_BLAZOR_APP_ID }}
      AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
      AZURE_Z_LOCATION: ${{ vars.AZURE_Z_LOCATION }}
      SERVICE_MY_BLAZOR_APP_IMAGE_NAME: ${{ vars.SERVICE_MY_BLAZOR_APP_IMAGE_NAME }}
      SERVICE_MY_BLAZOR_APP_RESOURCE_EXISTS: ${{ vars.SERVICE_MY_BLAZOR_APP_RESOURCE_EXISTS }}
      ENVIRONMENT_NAME: ${{ vars.AZURE_PROD_ENVIRONMENT_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install azd
        uses: Azure/setup-azd@v2
      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh
      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
          ENVIRONMENT_NAME: ${{ vars.AZURE_PROD_ENVIRONMENT_NAME }}
          environmentName: ${{ vars.AZURE_PROD_ENVIRONMENT_NAME }}
      - name: Set AZURE_RESOURCE_GROUP
        run: |
          echo "AZURE_RESOURCE_GROUP=${AZURE_Z_LOCATION}-${AZURE_SUBSCRIPTION}-${APPLICATION_NAME}-${ENVIRONMENT_NAME}-${APPLICATION_VERSION}-rg" >> $GITHUB_ENV
      - name: Deploy Application
        run: azd deploy --no-prompt
        env:
          AZURE_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
